load("@rules_haskell//haskell:defs.bzl", "haskell_binary")

haskell_binary(
    name = "apigen",
    srcs = ["apigen.hs"],
    tags = [
        "haskell",
        "no-cross",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//hs-apigen",
        "//hs-cimple",
        "//third_party/haskell:aeson",
        "//third_party/haskell:aeson-pretty",
        "//third_party/haskell:base",
        "//third_party/haskell:bytestring",
        "//third_party/haskell:containers",
        "//third_party/haskell:directory",
        "//third_party/haskell:filepath",
        "//third_party/haskell:optparse-applicative",
        "//third_party/haskell:text",
    ],
)
